CREATE TABLE users (
	user_id SERIAL PRIMARY KEY NOT NULL,
	username VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
);

CREATE TABLE posts (
	post_id SERIAL PRIMARY KEY NOT NULL,
	title VARCHAR(100) NOT NULL,
	content VARCHAR(240) NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
);

CREATE TABLE comments (
	comment_id SERIAL PRIMARY KEY NOT NULL,
	comment VARCHAR(255) NOT NULL,
	user_id INTEGER NOT NULL,
	post_id INTEGER NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
	FOREIGN KEY (post_id) REFERENCES posts (post_id) ON DELETE CASCADE
);

CREATE TABLE likes (
	like_id SERIAL PRIMARY KEY NOT NULL,
	user_id INTEGER NOT NULL,
	post_id INTEGER NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
	FOREIGN KEY (post_id) REFERENCES posts (post_id) ON DELETE CASCADE
);